# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bs_theme', '0003_userscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscore',
            old_name='user',
            new_name='user_id',
        ),
    ]
