# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_theme', '0004_auto_20161030_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='points_limited',
            field=models.BooleanField(default=True),
        ),
    ]
